server.port=5000

spring.data.mongodb.uri=mongodb+srv://tanishqchauhan873_db_user:Anmol2006@cluster0.bc7eoj6.mongodb.net/naukrisaathi?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=naukrisaathi

app.jwt.secret=NaukriSaathiSuperSecretKey2024ChangeThisInProductionToALongRandomString
app.jwt.expiration=86400000

logging.level.com.naukrisaathi=DEBUG